apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  destination:
    server: https://192.168.100.6:6443
    namespace: default
  source:
    repoURL: https://github.com/HafizAhmadJamil/k3s.git
    targetRevision: HEAD
    path: common/base-nginx
    helm:
      values: |
        ingress:
          host: nginx.ksa-jed.lab.net
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
