apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  destination:
    server: https://192.168.100.6:6443
    namespace: default
  source:
    repoURL: https://github.com/HafizAhmadJamil/k3s.git
    targetRevision: HEAD
    path: clusters/ksa-jed/apps/nginx
    plugin: null
    directory:
      recurse: true
  sourceType: kustomize
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
