apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../common/base-nginx

patches:
  - path: nginx-ingress-patch.yaml
    target:
      kind: Ingress
      name: nginx
      namespace: default
